// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-mock-exams.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_mock_exams_default = defineTool({
  name: "list_mock_exams",
  title: "List mock exams",
  description: "List AI-generated mock exams visible to the signed-in user (a student sees their own; a parent sees the ones they created).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Max exams to return"),
    status: z.enum(["scheduled", "in_progress", "completed"]).optional().describe("Optional status filter")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("ai_mock_exams").select("id, title, subjects, status, num_questions, scheduled_start, scheduled_end, created_at").order("scheduled_start", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { exams: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/log-study-session.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var log_study_session_default = defineTool2({
  name: "log_study_session",
  title: "Log a study session",
  description: "Record a study session (subject, minutes, questions attempted, score) for the signed-in student. Date defaults to today.",
  inputSchema: {
    subject: z2.string().trim().min(1).describe("Subject studied (e.g. Maths, VR, NVR, English)"),
    minutes: z2.number().int().min(0).max(600).describe("Minutes spent studying"),
    questions: z2.number().int().min(0).max(1e3).default(0).describe("Questions attempted"),
    score: z2.number().int().min(0).max(1e3).default(0).describe("Questions answered correctly"),
    date: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Optional date (YYYY-MM-DD); defaults to today")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async ({ subject, minutes, questions, score, date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const row = {
      user_id: ctx.getUserId(),
      subject,
      minutes,
      questions,
      score
    };
    if (date) row.date = date;
    const { data, error } = await supabaseForUser2(ctx).from("daily_logs").insert(row).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged ${minutes}m of ${subject}.` }],
      structuredContent: { log: data }
    };
  }
});

// src/lib/mcp/tools/list-recent-logs.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_logs_default = defineTool3({
  name: "list_recent_logs",
  title: "List recent study logs",
  description: "Return the signed-in user's most recent daily study logs.",
  inputSchema: {
    limit: z3.number().int().min(1).max(60).default(14).describe("How many recent logs to return")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("daily_logs").select("id, date, subject, minutes, questions, score").order("date", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { logs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool4({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's id, display name, and role (parent or student).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = supabaseForUser4(ctx);
    const uid = ctx.getUserId();
    const [{ data: profile }, { data: role }] = await Promise.all([
      client.from("profiles").select("display_name").eq("id", uid).maybeSingle(),
      client.from("user_roles").select("role").eq("user_id", uid).maybeSingle()
    ]);
    const info = {
      user_id: uid,
      email: ctx.getUserEmail() ?? null,
      display_name: profile?.display_name ?? null,
      role: role?.role ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gztffbygqnxhgaxhvlrk";
var mcp_default = defineMcp({
  name: "studyquest-mcp",
  title: "StudyQuest MCP",
  version: "0.1.0",
  instructions: "Tools for StudyQuest, an 11+ exam prep app. Use `whoami` to check the signed-in user, `list_mock_exams` to see AI mock exams, `list_recent_logs` to view study history, and `log_study_session` to record a study session.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_mock_exams_default, list_recent_logs_default, log_study_session_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
